import axios from "axios";
const api=axios.create({baseURL:import.meta.env.VITE_JAVA_BACKEND_BASE_URL||"http://localhost:8080",headers:{"Content-Type":"application/json"}});
api.interceptors.request.use(c=>{const t=localStorage.getItem("token");if(t)c.headers.Authorization=`Bearer ${t}`;return c;});
const u=r=>r.data;
export const registerCustomer=d=>api.post("/api/auth/register",d).then(u);
export const loginCustomer=d=>api.post("/api/auth/login",d).then(u);
export const getEligibleVehicles=p=>api.get("/api/vehicles/eligible",{params:p}).then(u);
export const getVehicle=id=>api.get(`/api/vehicles/${id}`).then(u);
export const createBooking=d=>api.post("/api/bookings",d).then(u);
export const getBooking=id=>api.get(`/api/bookings/${id}`).then(u);
export const getMyBookings=()=>api.get("/api/customer/bookings").then(u);
export const cancelBooking=id=>api.put(`/api/bookings/${id}/cancel`).then(u);
export const checkEVFeasibility=d=>api.post("/api/ev/feasibility",d).then(u);
export const getChargingStations=p=>api.get("/api/charging-stations/near-route",{params:p}).then(u);
export const uploadDocument=d=>api.post("/api/documents",d,{headers:{"Content-Type":"multipart/form-data"}}).then(u);
export const getDocument=id=>api.get(`/api/documents/${id}`).then(u);
export const submitBeforeCondition=(id,d)=>api.post(`/api/rentals/${id}/condition/before`,d,{headers:{"Content-Type":"multipart/form-data"}}).then(u);
export const submitAfterCondition=(id,d)=>api.post(`/api/rentals/${id}/condition/after`,d,{headers:{"Content-Type":"multipart/form-data"}}).then(u);
export const compareCondition=id=>api.post(`/api/rentals/${id}/condition/compare`).then(u);
export const createDispute=d=>api.post("/api/disputes",d).then(u);
export const getDispute=id=>api.get(`/api/disputes/${id}`).then(u);
export const getNotifications=()=>api.get("/api/notifications").then(u);
export const markNotificationRead=id=>api.put(`/api/notifications/${id}/read`).then(u);
export const getErrorMessage=(e,f="Something went wrong. Please try again.")=>e?.response?.data?.message||e?.response?.data?.error||(typeof e?.response?.data==="string"?e.response.data:null)||e?.message||f;
export default api;